name: Build and Push User Services

on:
  push:
    branches:
      - main
      - phase-1
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./templates/build-push-template.yml
    secrets: inherit
